### ISSUE TITLE
Todo: inventory-improvements

### ISSUE THREAD

**Issue by langbakk** [langbakk/HSS#107]
- [x] Alternate backgrounds for the list-items
- [x] Hover-background on hovering over the list
- [x] diversion between list and info (and/or new scrollbar)
- [x] Check font - outline, other font - something a bit more readable

**Comment by StudioErrilhl** [comment]
This is finished
