### ISSUE TITLE
Todo: finish the automated location function

### ISSUE THREAD

**Issue by StudioErrilhl** [langbakk/HSS#262]
Things to do:
- [ ] position FS and FM in their night locations at night (currently room, bathroom) - this will extend as the game progresses (create a night-time list for this)
- [ ] make sure that if status is "sleep" that FS and FM stays in their room(s)
- [ ] integrate their position into the image-map
- [ ] integrate their position-changes into the time-function (although, make sure that it only happens on full-hour movements, perhaps)
